<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TimelinesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     * 
     * Format:
     *      [
                'artist_id' => 1,
                'order' => '1',
                'date' => '',
                'title' => '',
                'text' => '',
            ],
     */
    public function run()
    {
        DB::table('timelines')->insert([
            // 1: Pauline Auzou
            [
                'artist_id' => 1,
                'order' => '1',
                'date' => '1775',
                'title' => 'Born on March 24 in Paris.',
                'text' => '',
            ],
            [
                'artist_id' => 1,
                'order' => '2',
                'date' => 'By 1793',
                'title' => 'Exhibiting at the Salon.',
                'text' => '',
            ],
            [
                'artist_id' => 1,
                'order' => '3',
                'date' => '1793/94',
                'title' => 'Marries Charles-Marie Auzou.',
                'text' => '',
            ],
            [
                'artist_id' => 1,
                'order' => '4',
                'date' => '1794',
                'title' => 'Gives birth to first child, François-Victor.',
                'text' => '',
            ],
            [
                'artist_id' => 1,
                'order' => '5',
                'date' => '1810',
                'title' => 'Receives a commission from Napoleon to paint a commemorative work of marriage for Marie Louise of Austria.',
                'text' => '',
            ],
            [
                'artist_id' => 1,
                'order' => '6',
                'date' => '1812',
                'title' => 'Receives another commission from Napoleon to paint a commemorative work of marriage for Marie Louise of Austria.',
                'text' => '',
            ],
            [
                'artist_id' => 1,
                'order' => '7',
                'date' => '1835',
                'title' => 'Dies on May 15 in Paris.',
                'text' => '',
            ],
            // 2: Madeleine-Françoise Basseporte
            [
                'artist_id' => 2,
                'order' => '1',
                'date' => '1701',
                'title' => 'Born on April 28 in Paris.',
                'text' => '',
            ],
            [
                'artist_id' => 2,
                'order' => '2',
                'date' => '1741',
                'title' => 'Succeeds Aubriet as official painter to the Jardin du roi.',
                'text' => '',
            ],
            [
                'artist_id' => 2,
                'order' => '3',
                'date' => '1780',
                'title' => 'Dies on September 6 in Paris.',
                'text' => '',
            ],
            // 3: Hester Bateman
            [
                'artist_id' => 3,
                'order' => '1',
                'date' => '1708',
                'title' => 'Born in London.',
                'text' => '',
            ],
            [
                'artist_id' => 3,
                'order' => '2',
                'date' => '1723',
                'title' => 'Marries gold chain maker and wire drawer John Bateman.',
                'text' => '',
            ],
            [
                'artist_id' => 3,
                'order' => '3',
                'date' => '1760',
                'title' => 'Takes over the family business following her husband’s death.',
                'text' => '',
            ],
            [
                'artist_id' => 3,
                'order' => '4',
                'date' => '1790',
                'title' => 'Retires from the business and is succeeded by her sons.',
                'text' => '',
            ],
            [
                'artist_id' => 3,
                'order' => '5',
                'date' => '1794',
                'title' => 'Dies on September 16 in London.',
                'text' => '',
            ],
            // 4: Mary Beale
            [
                'artist_id' => 4,
                'order' => '1',
                'date' => '1633',
                'title' => 'Born in Suffolk.',
                'text' => '',
            ],
            [
                'artist_id' => 4,
                'order' => '2',
                'date' => '1650s',
                'title' => 'Befriends Sir Peter Lely, court painter to Charles II, king of England.',
                'text' => '',
            ],
            [
                'artist_id' => 4,
                'order' => '3',
                'date' => '1651',
                'title' => 'Marries Charles Beale.',
                'text' => '',
            ],
            [
                'artist_id' => 4,
                'order' => '4',
                'date' => '1665',
                'title' => 'Leaves London to escape the Great Plague.',
                'text' => '',
            ],
            [
                'artist_id' => 4,
                'order' => '5',
                'date' => '1666',
                'title' => 'Writes the manuscript <i>Discourse on Friendship.</i>',
                'text' => '',
            ],
            [
                'artist_id' => 4,
                'order' => '6',
                'date' => '1677',
                'title' => 'Son Charles begins to study miniature painting.',
                'text' => '',
            ],
            [
                'artist_id' => 4,
                'order' => '7',
                'date' => '1681',
                'title' => 'Takes on two students, Keaty Trioche and Mr. More.',
                'text' => '',
            ],
            [
                'artist_id' => 4,
                'order' => '8',
                'date' => '1691',
                'title' => 'Takes on Sarah Curtis as a student.',
                'text' => '',
            ],
            [
                'artist_id' => 4,
                'order' => '9',
                'date' => '1699',
                'title' => 'Dies on October 8 in London and is buried at St. James’ Church Piccadilly.',
                'text' => '',
            ],
            // 5: Marie-Guillemine Benoist
            [
                'artist_id' => 5,
                'order' => '1',
                'date' => '1768',
                'title' => 'Born in Paris.',
                'text' => '',
            ],
            [
                'artist_id' => 5,
                'order' => '2',
                'date' => '1780s',
                'title' => 'Along with her sister, studies with both Jacques-Louis David and Elisabeth Vigée le Brun.',
                'text' => '',
            ],
            [
                'artist_id' => 5,
                'order' => '3',
                'date' => '1784–89',
                'title' => 'Exhibits annually at the place Dauphine on the Île de la Cité.',
                'text' => '',
            ],
            [
                'artist_id' => 5,
                'order' => '4',
                'date' => '1791',
                'title' => 'Exhibits three narrative paintings at the Louvre.',
                'text' => '',
            ],
            [
                'artist_id' => 5,
                'order' => '5',
                'date' => '1793',
                'title' => 'Marries Pierre-Vincent Benoist, who is soon forced to flee France to avoid arrest for plotting Marie Antoinette\'s rescue from prison.',
                'text' => '',
            ],
            [
                'artist_id' => 5,
                'order' => '6',
                'date' => '1795',
                'title' => 'Reunites with her husband.',
                'text' => '',
            ],
            [
                'artist_id' => 5,
                'order' => '7',
                'date' => 'After 1799',
                'title' => 'Participates with other artists in the Ministry of the Interior to circulate images of Napoleon and the imperial family throughout the First Empire.',
                'text' => '',
            ],
            [
                'artist_id' => 5,
                'order' => '8',
                'date' => '1800',
                'title' => 'Exhibits <i>Portrait of Madeline</i> at the Salon.',
                'text' => '',
            ],
            [
                'artist_id' => 5,
                'order' => '9',
                'date' => '1804',
                'title' => 'Awarded a gold medal in the Salon.',
                'text' => '',
            ],
            [
                'artist_id' => 5,
                'order' => '10',
                'date' => '1804',
                'title' => 'Opens a school for girls.',
                'text' => '',
            ],
            [
                'artist_id' => 5,
                'order' => '11',
                'date' => '1815',
                'title' => 'Ends her carer as an artist when Pierre-Vincent Benoist is appointed to the Council of State.',
                'text' => '',
            ],
            [
                'artist_id' => 5,
                'order' => '12',
                'date' => '1826',
                'title' => 'Dies in Paris.',
                'text' => '',
            ],
            // 6: Mary Benwell
            [
                'artist_id' => 6,
                'order' => '1',
                'date' => '1739',
                'title' => 'Born in England.',
                'text' => '',
            ],
            [
                'artist_id' => 6,
                'order' => '2',
                'date' => '1762',
                'title' => 'Marries a military officer, Robert Codd.',
                'text' => '',
            ],
            [
                'artist_id' => 6,
                'order' => '3',
                'date' => '1762',
                'title' => 'Begins exhibiting prolifically at the Society of Artists.',
                'text' => '',
            ],
            [
                'artist_id' => 6,
                'order' => '4',
                'date' => '1769',
                'title' => 'Becomes an honorary member of the Society of Artists.',
                'text' => '',
            ],
            [
                'artist_id' => 6,
                'order' => '5',
                'date' => '1775',
                'title' => 'Begins exhibiting at the Royal Academy.',
                'text' => '',
            ],
            [
                'artist_id' => 6,
                'order' => '6',
                'date' => '1791',
                'title' => 'Exhibits at the Society of Artists.',
                'text' => '',
            ],
            [
                'artist_id' => 6,
                'order' => '7',
                'date' => '1811',
                'title' => 'Dies in London.',
                'text' => '',
            ],
            // 7: Marie-Geneviève Bouliar
            [
                'artist_id' => 7,
                'order' => '1',
                'date' => '1763',
                'title' => 'Born in Paris.',
                'text' => '',
            ],
            [
                'artist_id' => 7,
                'order' => '2',
                'date' => '1791',
                'title' => 'Begins exhibiting regularly at the Salon.',
                'text' => '',
            ],
            [
                'artist_id' => 7,
                'order' => '3',
                'date' => '1817',
                'title' => 'Last exhibition at the Salon.',
                'text' => '',
            ],
            [
                'artist_id' => 7,
                'order' => '4',
                'date' => '1825',
                'title' => 'Dies in Saône-et-Loire.',
                'text' => '',
            ],
            // 8: Marie-Gabrielle Capet
            [
                'artist_id' => 8,
                'order' => '1',
                'date' => '1761',
                'title' => 'Born in Lyon.',
                'text' => '',
            ],
            [
                'artist_id' => 8,
                'order' => '2',
                'date' => '1781',
                'title' => 'Moves to Paris and becomes a student of Adélaïde Labille-Guiard.',
                'text' => '',
            ],
            [
                'artist_id' => 8,
                'order' => '3',
                'date' => '1781–82',
                'title' => 'Exhibits drawings at the Exposition de la Jeunesse and the Salon de Correspondance.',
                'text' => '',
            ],
            [
                'artist_id' => 8,
                'order' => '4',
                'date' => '1783',
                'title' => 'Exhibits at the Salon de la Jeunesse.',
                'text' => '',
            ],
            [
                'artist_id' => 8,
                'order' => '5',
                'date' => '1786',
                'title' => 'Shows work at the Salon de la Correspondance.',
                'text' => '',
            ],
            [
                'artist_id' => 8,
                'order' => '6',
                'date' => '1803',
                'title' => 'Places painting career on hold to care for Adélaïde Labille-Guiard.',
                'text' => '',
            ],
            [
                'artist_id' => 8,
                'order' => '7',
                'date' => '1814',
                'title' => 'Completes last dated work.',
                'text' => '',
            ],
            [
                'artist_id' => 8,
                'order' => '8',
                'date' => '1818',
                'title' => 'Dies in Paris.',
                'text' => '',
            ],
            // 9: Joan Carlile
            [
                'artist_id' => 9,
                'order' => '1',
                'date' => 'ca. 1606',
                'title' => 'Born in London.',
                'text' => '',
            ],
            [
                'artist_id' => 9,
                'order' => '2',
                'date' => '1626',
                'title' => 'Marries poet and court dramatist Lodowick Carlile.',
                'text' => '',
            ],
            [
                'artist_id' => 9,
                'order' => '3',
                'date' => '1654',
                'title' => 'Moves to Covent Garden.',
                'text' => '',
            ],
            [
                'artist_id' => 9,
                'order' => '4',
                'date' => '1675',
                'title' => 'Death of Lodowick Carlile',
                'text' => '',
            ],
            [
                'artist_id' => 9,
                'order' => '5',
                'date' => '1679',
                'title' => 'Dies in London.',
                'text' => '',
            ],
            // 10: Julie Charpentier
            [
                'artist_id' => 10,
                'order' => '1',
                'date' => '1770',
                'title' => 'Born in Paris.',
                'text' => '',
            ],
            [
                'artist_id' => 10,
                'order' => '2',
                'date' => '1787',
                'title' => 'Begins exhibiting.',
                'text' => '',
            ],
            [
                'artist_id' => 10,
                'order' => '3',
                'date' => '1793',
                'title' => 'Debuts at the Salon.',
                'text' => '',
            ],
            [
                'artist_id' => 10,
                'order' => '4',
                'date' => '1801',
                'title' => 'Begins working for the Muséum d’histoire naturelle.',
                'text' => '',
            ],
            [
                'artist_id' => 10,
                'order' => '5',
                'date' => '1826',
                'title' => 'Receives a salaried post at the Muséum d’histoire naturelle.',
                'text' => '',
            ],
            [
                'artist_id' => 10,
                'order' => '6',
                'date' => '1843',
                'title' => 'Dies in Paris.',
                'text' => '',
            ],
            // 11: Élisabeth Sophie Chéron
            [
                'artist_id' => 11,
                'order' => '1',
                'date' => '1648',
                'title' => 'Born in Paris on October 3.',
                'text' => '',
            ],
            [
                'artist_id' => 11,
                'order' => '2',
                'date' => '1670',
                'title' => 'Admitted to the Académie Royale de Peinture et de Sculpture with the support of Charles Le Brun. She was the fourth woman artist to enter the Academy.',
                'text' => '',
            ],
            [
                'artist_id' => 11,
                'order' => '3',
                'date' => '1699',
                'title' => 'Elected to the Accademia dei Ricovrati, in Padua, with the academician name Erato.',
                'text' => '',
            ],
            [
                'artist_id' => 11,
                'order' => '4',
                'date' => '1708',
                'title' => 'Marries Jacques Le Hay',
                'text' => '',
            ],
            [
                'artist_id' => 11,
                'order' => '5',
                'date' => '1711',
                'title' => 'Dies in Paris on September 3.',
                'text' => '',
            ],
            // 12: Marie-Anne Collot
            [
                'artist_id' => 12,
                'order' => '1',
                'date' => '1748',
                'title' => 'Born in Paris.',
                'text' => '',
            ],
            [
                'artist_id' => 12,
                'order' => '2',
                'date' => '1763',
                'title' => 'Working as a model for the artist Jean-Baptiste II Lemoyne.',
                'text' => '',
            ],
            [
                'artist_id' => 12,
                'order' => '3',
                'date' => '1763',
                'title' => 'Enters the atelier of Etienne Falconet.',
                'text' => '',
            ],
            [
                'artist_id' => 12,
                'order' => '4',
                'date' => '1765',
                'title' => 'Completes earliest dated portrait bust.',
                'text' => '',
            ],
            [
                'artist_id' => 12,
                'order' => '5',
                'date' => '1766',
                'title' => 'Visits Saint Petersburg at the invitation of Catherine the Great.',
                'text' => '',
            ],
            [
                'artist_id' => 12,
                'order' => '6',
                'date' => '1766',
                'title' => 'Presents at the Imperial Academy of Arts.',
                'text' => '',
            ],
            [
                'artist_id' => 12,
                'order' => '7',
                'date' => '1767',
                'title' => 'Elected a member of the Imperial Academy of Arts, first known woman artist to receive this rank in Russia.',
                'text' => '',
            ],
            [
                'artist_id' => 12,
                'order' => '8',
                'date' => '1769',
                'title' => 'Father dies under mysterious circumstances.',
                'text' => '',
            ],
            [
                'artist_id' => 12,
                'order' => '9',
                'date' => '1777',
                'title' => 'Marries Pierre-Etienne Falconet, the son of her teacher, Etienne Falconet, in Saint Petersburg.',
                'text' => '',
            ],
            [
                'artist_id' => 12,
                'order' => '10',
                'date' => '1778',
                'title' => 'Gives birth to a daughter, with whom she later returns to Paris.',
                'text' => '',
            ],
            [
                'artist_id' => 12,
                'order' => '11',
                'date' => '1791',
                'title' => 'Buys an estate at Marimont for retirement.',
                'text' => '',
            ],
            [
                'artist_id' => 12,
                'order' => '12',
                'date' => '1821',
                'title' => 'Dies in Nancy.',
                'text' => '',
            ],
            // 13: Maria Hadfield Cosway
            [
                'artist_id' => 13,
                'order' => '1',
                'date' => '1760',
                'title' => 'Born on June 11 in Florence to an Italian mother and English father.',
                'text' => '',
            ],
            [
                'artist_id' => 13,
                'order' => '2',
                'date' => '1773',
                'title' => 'Begins copying Old Masters in the Uffizi Gallery.',
                'text' => '',
            ],
            [
                'artist_id' => 13,
                'order' => '3',
                'date' => '1778',
                'title' => 'Elected into the Accademia del Disegno in Florence.',
                'text' => '',
            ],
            [
                'artist_id' => 13,
                'order' => '4',
                'date' => '1778',
                'title' => 'Leaves Florence for Rome.',
                'text' => '',
            ],
            [
                'artist_id' => 13,
                'order' => '5',
                'date' => '1779',
                'title' => 'Moves to London',
                'text' => '',
            ],
            [
                'artist_id' => 13,
                'order' => '6',
                'date' => '1781',
                'title' => 'Exhibits for the first time at the Royal Academy of the Arts in London.',
                'text' => '',
            ],
            [
                'artist_id' => 13,
                'order' => '7',
                'date' => '1781',
                'title' => 'Marries fellow artist and miniature portrait painter Richard Cosway.',
                'text' => '',
            ],
            [
                'artist_id' => 13,
                'order' => '8',
                'date' => '1786',
                'title' => 'In Paris, John Trumball introduces the Cosways to Thomas Jefferson.',
                'text' => '',
            ],
            [
                'artist_id' => 13,
                'order' => '9',
                'date' => '1801',
                'title' => 'In Paris, begins copying Old Master paintings from the Louvre for publication in England.',
                'text' => '',
            ],
            [
                'artist_id' => 13,
                'order' => '10',
                'date' => '1803–1809',
                'title' => 'Directs a school for girls in Paris.',
                'text' => '',
            ],
            [
                'artist_id' => 13,
                'order' => '11',
                'date' => '1809',
                'title' => 'Establishes a convent and Catholic school for girls in Lodi, near Milan.',
                'text' => '',
            ],
            [
                'artist_id' => 13,
                'order' => '12',
                'date' => '1821',
                'title' => 'Returns to England to care for dying husband with help from her friend Sir John Soane.',
                'text' => '',
            ],
            [
                'artist_id' => 13,
                'order' => '13',
                'date' => '1838',
                'title' => 'Dies at her school in Lodi.',
                'text' => '',
            ],
            // 14: Anne Seymour Damer
            [
                'artist_id' => 14,
                'order' => '1',
                'date' => '1748',
                'title' => 'Born on November 8.',
                'text' => '',
            ],
            [
                'artist_id' => 14,
                'order' => '2',
                'date' => 'ca. 1762',
                'title' => 'Completes earliest surviving works, mostly drawings and sketches.',
                'text' => '',
            ],
            [
                'artist_id' => 14,
                'order' => '3',
                'date' => '1767',
                'title' => 'Marries John Damer, son of Lord Milton, later the 1st Earl of Dorchester.',
                'text' => '',
            ],
            [
                'artist_id' => 14,
                'order' => '4',
                'date' => '1776',
                'title' => 'Death of John Damer.',
                'text' => '',
            ],
            [
                'artist_id' => 14,
                'order' => '5',
                'date' => '1778',
                'title' => 'First trip to Italy.',
                'text' => '',
            ],
            [
                'artist_id' => 14,
                'order' => '6',
                'date' => '1784',
                'title' => 'Begins exhibiting as an amateur at the Royal Academy.',
                'text' => '',
            ],
            [
                'artist_id' => 14,
                'order' => '7',
                'date' => '1797',
                'title' => 'Inherits Strawberry Hill from her cousin Horace Walpole.',
                'text' => '',
            ],
            [
                'artist_id' => 14,
                'order' => '8',
                'date' => '1802',
                'title' => 'Visits Paris with Mary Berry during the Peace of Amiens.',
                'text' => '',
            ],
            [
                'artist_id' => 14,
                'order' => '9',
                'date' => '1818',
                'title' => 'Moves to York House in Twickenham.',
                'text' => '',
            ],
            [
                'artist_id' => 14,
                'order' => '10',
                'date' => '1828',
                'title' => 'Dies on May 28.',
                'text' => '',
            ],
            // 15: Mary Delany
            [
                'artist_id' => 15,
                'order' => '1',
                'date' => '1700',
                'title' => 'Born in Wiltshire.',
                'text' => '',
            ],
            [
                'artist_id' => 15,
                'order' => '2',
                'date' => '1770',
                'title' => 'Begins working in a self-developed cut-paper technique to create botanical illustrations.',
                'text' => '',
            ],
            [
                'artist_id' => 15,
                'order' => '3',
                'date' => '1788',
                'title' => 'Dies in London.',
                'text' => '',
            ],
            // 16: Volcxken Diericx
            [
                'artist_id' => 16,
                'order' => '1',
                'date' => 'ca. 1525',
                'title' => 'Born in Antwerp.',
                'text' => '',
            ],
            [
                'artist_id' => 16,
                'order' => '2',
                'date' => '1547',
                'title' => 'Marries Hieronymus Cock, an important printmaker and publisher.',
                'text' => '',
            ],
            [
                'artist_id' => 16,
                'order' => '3',
                'date' => '1548',
                'title' => 'Opens Aux Quatre Vents publishing house with her husband.',
                'text' => '',
            ],
            [
                'artist_id' => 16,
                'order' => '4',
                'date' => '1570',
                'title' => 'Hieronymus Cock dies.',
                'text' => '',
            ],
            [
                'artist_id' => 16,
                'order' => '5',
                'date' => '1600',
                'title' => 'Dies in Antwerp.',
                'text' => '',
            ],
            // 17: Barbara Regina Dietzsch
            [
                'artist_id' => 17,
                'order' => '1',
                'date' => '1706',
                'title' => 'Born on September 22 in Nuremberg.',
                'text' => '',
            ],
            [
                'artist_id' => 17,
                'order' => '2',
                'date' => '1783',
                'title' => 'Dies on May 1 in Nuremberg.',
                'text' => '',
            ],
            // 18: Françoise Duparc
            [
                'artist_id' => 18,
                'order' => '1',
                'date' => '1726',
                'title' => 'Born in Murcia, Spain.',
                'text' => '',
            ],
            [
                'artist_id' => 18,
                'order' => '2',
                'date' => '1730',
                'title' => 'Family returns to their hometown of Marseilles.',
                'text' => '',
            ],
            [
                'artist_id' => 18,
                'order' => '3',
                'date' => '1742–45',
                'title' => 'Apprentices with Jean-Baptiste van Loo in Aix-en-Provence.',
                'text' => '',
            ],
            [
                'artist_id' => 18,
                'order' => '4',
                'date' => '1763 and 1766',
                'title' => 'Exhibits in London at Free Society of Artists.',
                'text' => '',
            ],
            [
                'artist_id' => 18,
                'order' => '5',
                'date' => '1771',
                'title' => 'Returns to Marseilles.',
                'text' => '',
            ],
            [
                'artist_id' => 18,
                'order' => '6',
                'date' => '1776',
                'title' => 'Becomes a member of the Academy in Marseilles.',
                'text' => '',
            ],
            [
                'artist_id' => 18,
                'order' => '7',
                'date' => '1778',
                'title' => 'Dies in Marseilles.',
                'text' => '',
            ],
            // 19: Maria Faydherbe
            [
                'artist_id' => 19,
                'order' => '1',
                'date' => '1587',
                'title' => 'Born in Mechelen.',
                'text' => '',
            ],
            [
                'artist_id' => 19,
                'order' => '2',
                'date' => '1632',
                'title' => 'Files request with the Mechelen city council to join the Guild of Saint Luke.',
                'text' => '',
            ],
            [
                'artist_id' => 19,
                'order' => '3',
                'date' => '1633',
                'title' => 'Request to join the Guild of Saint Luke is denied.',
                'text' => '',
            ],
            [
                'artist_id' => 19,
                'order' => '4',
                'date' => '1643',
                'title' => 'Dies in Mechelen.',
                'text' => '',
            ],
            // 20: Marguerite Gérard
            [
                'artist_id' => 20,
                'order' => '1',
                'date' => '1761',
                'title' => 'Born on January 28 in Grasse.',
                'text' => '',
            ],
            [
                'artist_id' => 20,
                'order' => '2',
                'date' => '1768',
                'title' => 'Her sister, Marie-Anne, marries Jean-Honoré Fragonard.',
                'text' => '',
            ],
            [
                'artist_id' => 20,
                'order' => '3',
                'date' => '1776',
                'title' => 'She moves to Paris to live with her sister as part of the Fragonard household.',
                'text' => '',
            ],
            [
                'artist_id' => 20,
                'order' => '4',
                'date' => 'ca. 1778',
                'title' => 'Completes etching collaborations with Fragonard.',
                'text' => '',
            ],
            [
                'artist_id' => 20,
                'order' => '5',
                'date' => '1779',
                'title' => 'Exhibits at the Salon de la Correspondance.',
                'text' => '',
            ],
            [
                'artist_id' => 20,
                'order' => '6',
                'date' => '1790',
                'title' => 'Exhibits at the Exposition de la Société des Amis des Arts.',
                'text' => '',
            ],
            [
                'artist_id' => 20,
                'order' => '7',
                'date' => '1794',
                'title' => 'Awarded 2,000 livres in the Concours de l\'An.',
                'text' => '',
            ],
            [
                'artist_id' => 20,
                'order' => '8',
                'date' => '1799',
                'title' => 'Exhibits at the Paris Salon and wins Prix du 5<sup>ème</sup> Classe.',
                'text' => '',
            ],
            [
                'artist_id' => 20,
                'order' => '9',
                'date' => '1801',
                'title' => 'Exhibits at the Paris Salon and wins Prix d\'Encouragement.',
                'text' => '',
            ],
            [
                'artist_id' => 20,
                'order' => '10',
                'date' => '1804',
                'title' => 'Exhibits at the Paris Salon and wins Médaille d\'Or.',
                'text' => '',
            ],
            [
                'artist_id' => 20,
                'order' => '11',
                'date' => '1806',
                'title' => 'Fragonard dies.',
                'text' => '',
            ],
            [
                'artist_id' => 20,
                'order' => '12',
                'date' => '1808',
                'title' => '<i>Clemency of Napoleon</i> is purchased by Emperor Napoleon.',
                'text' => '',
            ],
            [
                'artist_id' => 20,
                'order' => '13',
                'date' => '1823',
                'title' => 'Death of her sister Marie-Anne.',
                'text' => '',
            ],
            [
                'artist_id' => 20,
                'order' => '14',
                'date' => '1824',
                'title' => 'Has final exhibition at the Paris Salon.',
                'text' => '',
            ],
            [
                'artist_id' => 20,
                'order' => '15',
                'date' => '1837',
                'title' => 'Dies on May 18 in Paris.',
                'text' => '',
            ],
            // 21: Marie-Suzanne Giroust
            [
                'artist_id' => 21,
                'order' => '1',
                'date' => '1734',
                'title' => 'Born in Paris on March 9.',
                'text' => '',
            ],
            [
                'artist_id' => 21,
                'order' => '2',
                'date' => '1741',
                'title' => 'Father dies.',
                'text' => '',
            ],
            [
                'artist_id' => 21,
                'order' => '3',
                'date' => '1745',
                'title' => 'Mother dies.',
                'text' => 'Giroust is subsequently raised by her grandmother Jean-Suzanne Le Sourt.',
            ],
            [
                'artist_id' => 21,
                'order' => '4',
                'date' => '1750s',
                'title' => 'Studies pastel drawing with Maurice Quentin de la Tour.',
                'text' => '',
            ],
            [
                'artist_id' => 21,
                'order' => '5',
                'date' => '1750s',
                'title' => 'Studies with and becomes friends with Joseph Vien.',
                'text' => '',
            ],
            [
                'artist_id' => 21,
                'order' => '6',
                'date' => '1759',
                'title' => 'Marries Alexander Roslin.',
                'text' => '',
            ],
            [
                'artist_id' => 21,
                'order' => '7',
                'date' => '1760',
                'title' => 'Gives birth to first child, Augustine Suzanne.',
                'text' => '',
            ],
            [
                'artist_id' => 21,
                'order' => '8',
                'date' => '1761',
                'title' => 'Gives birth to second child, Alexandrine Elisabeth.',
                'text' => '',
            ],
            [
                'artist_id' => 21,
                'order' => '9',
                'date' => '1762',
                'title' => 'Gives birth to Charlotte Françoise.',
                'text' => '',
            ],
            [
                'artist_id' => 21,
                'order' => '10',
                'date' => '1763',
                'title' => 'Gives birth to Henri.',
                'text' => '',
            ],
            [
                'artist_id' => 21,
                'order' => '11',
                'date' => '1764',
                'title' => 'Gives birth to Alexandre-Antoine.',
                'text' => '',
            ],
            [
                'artist_id' => 21,
                'order' => '12',
                'date' => '1770',
                'title' => 'Admitted to the Académie Royale.',
                'text' => '',
            ],
            [
                'artist_id' => 21,
                'order' => '13',
                'date' => '1771',
                'title' => 'Exhibits at the Salon for the first and only time.',
                'text' => '',
            ],
            [
                'artist_id' => 21,
                'order' => '14',
                'date' => '1772',
                'title' => 'Gives birth to a son, Joseph.',
                'text' => '',
            ],
            [
                'artist_id' => 21,
                'order' => '15',
                'date' => '1772',
                'title' => 'Dies on August 31 of breast cancer.',
                'text' => '',
            ],
            // 22: Aleida Greve
            [
                'artist_id' => 22,
                'order' => '1',
                'date' => '1670',
                'title' => 'Born in Zwolle, Netherlands.',
                'text' => '',
            ],
            [
                'artist_id' => 22,
                'order' => '2',
                'date' => '1686',
                'title' => 'Becomes a student of Dordrecht painter Wilhelmus Beurs.',
                'text' => '',
            ],
            [
                'artist_id' => 22,
                'order' => '3',
                'date' => '1706',
                'title' => 'Purchases a house in Zwolle that formerly belonged to the artist Aleijda Wolfsen and begins to assemble a large art collection.',
                'text' => '',
            ],
            [
                'artist_id' => 22,
                'order' => '4',
                'date' => '1742',
                'title' => 'Dies on February 4 in Zwolle. Her will designates teh Zwolle house as a home for women.',
                'text' => '',
            ],
            // 23: Susanna Horenboult
            [
                'artist_id' => 23,
                'order' => '1',
                'date' => '1503',
                'title' => 'Born in Ghent',
                'text' => '',
            ],
            [
                'artist_id' => 23,
                'order' => '2',
                'date' => '1521',
                'title' => 'Meets Albrecht Dürer in Antwerp.',
                'text' => '',
            ],
            [
                'artist_id' => 23,
                'order' => '3',
                'date' => 'Later 1520s',
                'title' => 'Moves to England and marries John Parker, yeoman of Henry VIII\'s wardrobe.',
                'text' => '',
            ],
            [
                'artist_id' => 23,
                'order' => '4',
                'date' => '1532',
                'title' => 'Among the women offered New Year\'s gifts by Henry VIII.',
                'text' => '',
            ],
            [
                'artist_id' => 23,
                'order' => '5',
                'date' => '1537',
                'title' => 'Husband dies and, in the absence of children, his will bequeaths most of his possessions to his brother\'s family.',
                'text' => '',
            ],
            [
                'artist_id' => 23,
                'order' => '6',
                'date' => '1539',
                'title' => 'Marries John Gilman',
                'text' => '',
            ],
            [
                'artist_id' => 23,
                'order' => '7',
                'date' => '1539',
                'title' => 'Sent by Henry VIII to accompany Anne of Cleves to England and eventually becomes a Gentlewoman of the Privy Chamber.',
                'text' => '',
            ],
            [
                'artist_id' => 23,
                'order' => '8',
                'date' => 'early 1540s',
                'title' => 'Gives birth to children.',
                'text' => '',
            ],
            [
                'artist_id' => 23,
                'order' => '9',
                'date' => '1540-41',
                'title' => 'Receives land grants.',
                'text' => '',
            ],
            [
                'artist_id' => 23,
                'order' => '10',
                'date' => '1543',
                'title' => 'Attends Queen Catherine Parr.',
                'text' => '',
            ],
            [
                'artist_id' => 23,
                'order' => '11',
                'date' => '1554',
                'title' => 'Dies in England.',
                'text' => '',
            ],
            // 24: Johanna Koerten
            [
                'artist_id' => 24,
                'order' => '1',
                'date' => '1650',
                'title' => 'Born in Amsterdam.',
                'text' => '',
            ],
            [
                'artist_id' => 24,
                'order' => '2',
                'date' => '1651',
                'title' => 'Father dies.',
                'text' => '',
            ],
            [
                'artist_id' => 24,
                'order' => '3',
                'date' => '1659',
                'title' => 'Mother remarries.',
                'text' => '',
            ],
            [
                'artist_id' => 24,
                'order' => '4',
                'date' => '1669',
                'title' => 'Baptized in Amsterdam.',
                'text' => '',
            ],
            [
                'artist_id' => 24,
                'order' => '5',
                'date' => '1690s',
                'title' => 'Established as a producer of sophisticated works on paper.',
                'text' => '',
            ],
            [
                'artist_id' => 24,
                'order' => '6',
                'date' => '1691',
                'title' => 'Mother dies. Marries cloth merchant Adrian Blok.',
                'text' => '',
            ],
            [
                'artist_id' => 24,
                'order' => '7',
                'date' => '1697',
                'title' => 'Receives a visit from Peter the Great.',
                'text' => '',
            ],
            [
                'artist_id' => 24,
                'order' => '8',
                'date' => '1715',
                'title' => 'Dies on December 28 in Amsterdam and is buried in Oudezijds Chapel.',
                'text' => '',
            ],
            // 25: Adélaïde Labille-Guiard
            [
                'artist_id' => 25,
                'order' => '1',
                'date' => '1749',
                'title' => 'Born on April 11 in Paris.',
                'text' => '',
            ],
            [
                'artist_id' => 25,
                'order' => '2',
                'date' => 'ca. 1763–65',
                'title' => 'Studies with the painter François-Elie Vincent.',
                'text' => '',
            ],
            [
                'artist_id' => 25,
                'order' => '3',
                'date' => '1769',
                'title' => 'Becomes on of a group taught by Quentin de la Tour.',
                'text' => '',
            ],
            [
                'artist_id' => 25,
                'order' => '4',
                'date' => '1769',
                'title' => 'Marries Nicolas Guiard.',
                'text' => '',
            ],
            [
                'artist_id' => 25,
                'order' => '5',
                'date' => '1774',
                'title' => 'Joins the Académie de Saint-Luc.',
                'text' => '',
            ],
            [
                'artist_id' => 25,
                'order' => '6',
                'date' => '1776',
                'title' => 'Enters the studio of the academically trained history painter and portraitist François André Vincent.',
                'text' => '',
            ],
            [
                'artist_id' => 25,
                'order' => '7',
                'date' => '1782',
                'title' => 'Exhibits at the Salon de la Correspondance.',
                'text' => '',
            ],
            [
                'artist_id' => 25,
                'order' => '8',
                'date' => '1783',
                'title' => 'Admitted to the Académie Royale de Peinture et de Sculpture.',
                'text' => '',
            ],
            [
                'artist_id' => 25,
                'order' => '9',
                'date' => '1783',
                'title' => 'Begins exhibiting at the Salon.',
                'text' => '',
            ],
            [
                'artist_id' => 25,
                'order' => '10',
                'date' => '1787',
                'title' => 'Named official painter to Louis XVI\'s maiden aunts, Mesdames Adélaïde and Victoire.',
                'text' => '',
            ],
            [
                'artist_id' => 25,
                'order' => '11',
                'date' => '1790',
                'title' => 'Takes an active role in reforming the regulations of the Académie.',
                'text' => '',
            ],
            [
                'artist_id' => 25,
                'order' => '12',
                'date' => '1791',
                'title' => 'Presents a series of portraits of prominent members of the Assemblée National.',
                'text' => '',
            ],
            [
                'artist_id' => 25,
                'order' => '13',
                'date' => '1793',
                'title' => 'Divorces Nicolas Guiard.',
                'text' => '',
            ],
            [
                'artist_id' => 25,
                'order' => '14',
                'date' => '1795',
                'title' => 'Returns to an altered Paris after a countryside refuge during the Reign of Terror.',
                'text' => '',
            ],
            [
                'artist_id' => 25,
                'order' => '15',
                'date' => '1795',
                'title' => 'Obtains artist\'s lodging at the Louvre.',
                'text' => '',
            ],
            [
                'artist_id' => 25,
                'order' => '16',
                'date' => '1800',
                'title' => 'Marries former teacher, François-Elie Vincent.',
                'text' => '',
            ],
            [
                'artist_id' => 25,
                'order' => '17',
                'date' => '1803',
                'title' => 'Does on April 23 in Paris.',
                'text' => '',
            ],
            // 26: Marie-Victoire Lemoine
            [
                'artist_id' => 26,
                'order' => '1',
                'date' => '1754',
                'title' => 'Born in Paris.',
                'text' => '',
            ],
            [
                'artist_id' => 26,
                'order' => '2',
                'date' => '1779',
                'title' => 'Exhibits at the Salon de la Correspondance.',
                'text' => '',
            ],
            [
                'artist_id' => 26,
                'order' => '3',
                'date' => '1785',
                'title' => 'Exhibits at the Salon de la Correspondance.',
                'text' => '',
            ],
            [
                'artist_id' => 26,
                'order' => '4',
                'date' => '1796',
                'title' => 'Debuts at the Salon.',
                'text' => '',
            ],
            [
                'artist_id' => 26,
                'order' => '5',
                'date' => '1814',
                'title' => 'Has final Salon exhibition.',
                'text' => '',
            ],
            [
                'artist_id' => 26,
                'order' => '6',
                'date' => '1820',
                'title' => 'Dies in Paris.',
                'text' => '',
            ],
            // 27: Judith Leyster
            [
                'artist_id' => 27,
                'order' => '1',
                'date' => '1602',
                'title' => 'Born and baptized in Haarlem.',
                'text' => '',
            ],
            [
                'artist_id' => 27,
                'order' => '2',
                'date' => 'ca. 1626',
                'title' => 'May have worked in Frans Hals\'s workshop.',
                'text' => '',
            ],
            [
                'artist_id' => 27,
                'order' => '3',
                'date' => '1627',
                'title' => 'May have worked in the shop of Haarlem painter Frans Pietersz de Grebber.',
                'text' => '',
            ],
            [
                'artist_id' => 27,
                'order' => '4',
                'date' => '1633',
                'title' => 'Becomes the first female member of the Haarlem Guild of Saint Luke.',
                'text' => '',
            ],
            [
                'artist_id' => 27,
                'order' => '5',
                'date' => '1636',
                'title' => 'Marries painter Jan Miense Molenaer.',
                'text' => '',
            ],
            [
                'artist_id' => 27,
                'order' => '6',
                'date' => '1648',
                'title' => 'Moves to Heemstede with her husband.',
                'text' => '',
            ],
            [
                'artist_id' => 27,
                'order' => '7',
                'date' => '1660',
                'title' => 'Dies in Heemstede.',
                'text' => '',
            ],
            // 28: Marianne Loir
            [
                'artist_id' => 28,
                'order' => '1',
                'date' => 'ca. 1715',
                'title' => 'Born in Paris.',
                'text' => '',
            ],
            [
                'artist_id' => 28,
                'order' => '2',
                'date' => '1762',
                'title' => 'Elected a member of the Académie des Beaux-Arts in Marseilles.',
                'text' => '',
            ],
            [
                'artist_id' => 28,
                'order' => '3',
                'date' => '1769',
                'title' => 'Dies in Provence.',
                'text' => '',
            ],
            // 29: Maria Sibylla Merian
            [
                'artist_id' => 29,
                'order' => '1',
                'date' => '1647',
                'title' => 'Born in Frankfurt am Main.',
                'text' => '',
            ],
            [
                'artist_id' => 29,
                'order' => '2',
                'date' => '1650',
                'title' => 'Father, Matthäus Merian, dies.',
                'text' => '',
            ],
            [
                'artist_id' => 29,
                'order' => '3',
                'date' => '1651',
                'title' => 'Mother remarries the still life painter Jacob Marrel.',
                'text' => '',
            ],
            [
                'artist_id' => 29,
                'order' => '4',
                'date' => '1665',
                'title' => 'Marries painter Johann Andreas Graff.',
                'text' => '',
            ],
            [
                'artist_id' => 29,
                'order' => '5',
                'date' => '1668',
                'title' => 'Gives birth to first child, Johanna Helena Herolt, who becomes a botanical artist.',
                'text' => '',
            ],
            [
                'artist_id' => 29,
                'order' => '6',
                'date' => '1670',
                'title' => 'Moves with family to Nuremberg, her husband\'s hometown.',
                'text' => '',
            ],
            [
                'artist_id' => 29,
                'order' => '7',
                'date' => '1675',
                'title' => 'Publishes first book of natural illustrations.',
                'text' => '',
            ],
            [
                'artist_id' => 29,
                'order' => '8',
                'date' => '1678',
                'title' => 'Gives birth to second daughter.',
                'text' => '',
            ],
            [
                'artist_id' => 29,
                'order' => '9',
                'date' => '1678',
                'title' => 'Moves to Frankfurt am Main.',
                'text' => '',
            ],
            [
                'artist_id' => 29,
                'order' => '10',
                'date' => '1679',
                'title' => 'Publishes first volume of two-volume series on caterpillars.',
                'text' => '',
            ],
            [
                'artist_id' => 29,
                'order' => '11',
                'date' => '1681',
                'title' => 'Following death of her father, moves back in with her mother.',
                'text' => '',
            ],
            [
                'artist_id' => 29,
                'order' => '12',
                'date' => '1685',
                'title' => 'Joins Labadist community in Friesland.',
                'text' => '',
            ],
            [
                'artist_id' => 29,
                'order' => '13',
                'date' => '1691',
                'title' => 'Moves to Amsterdam.',
                'text' => '',
            ],
            [
                'artist_id' => 29,
                'order' => '14',
                'date' => '1692',
                'title' => 'Husband obtains a divorce.',
                'text' => '',
            ],
            [
                'artist_id' => 29,
                'order' => '15',
                'date' => '1699',
                'title' => 'Travels to Dutch Suriname.',
                'text' => '',
            ],
            [
                'artist_id' => 29,
                'order' => '16',
                'date' => '1701',
                'title' => 'Malaria forces a return to the Dutch Republic.',
                'text' => '',
            ],
            [
                'artist_id' => 29,
                'order' => '17',
                'date' => '1715',
                'title' => 'Suffers a stroke.',
                'text' => '',
            ],
            [
                'artist_id' => 29,
                'order' => '18',
                'date' => '1717',
                'title' => 'Dies in Amsterdam.',
                'text' => '',
            ],
            // 30: Eulalie Morin
            [
                'artist_id' => 30,
                'order' => '1',
                'date' => '1765',
                'title' => 'Born in Nantes',
                'text' => '',
            ],
            [
                'artist_id' => 30,
                'order' => '2',
                'date' => '1798',
                'title' => 'Begins exhibiting regularly at the Salon.',
                'text' => '',
            ],
            [
                'artist_id' => 30,
                'order' => '3',
                'date' => '1799',
                'title' => 'Completes her most famous work, <i>Portrait of Madame Récamier.</i>',
                'text' => '',
            ],
            [
                'artist_id' => 30,
                'order' => '4',
                'date' => '1837',
                'title' => 'Dies in Paris.',
                'text' => '',
            ],
            // 31: Mary Moser
            [
                'artist_id' => 31,
                'order' => '1',
                'date' => '1744',
                'title' => 'Born in London on October 27.',
                'text' => '',
            ],
            [
                'artist_id' => 31,
                'order' => '2',
                'date' => 'ca. 1750',
                'title' => 'Trained by her father.',
                'text' => '',
            ],
            [
                'artist_id' => 31,
                'order' => '3',
                'date' => '1758',
                'title' => 'Wins first Society of Arts medal at age fourteen.',
                'text' => '',
            ],
            [
                'artist_id' => 31,
                'order' => '4',
                'date' => '1759',
                'title' => 'Wins second Society of the Arts Medal age fifteen.',
                'text' => '',
            ],
            [
                'artist_id' => 31,
                'order' => '5',
                'date' => '1760',
                'title' => 'Begins exhibiting oils and watercolors at the Society of Artists.',
                'text' => '',
            ],
            [
                'artist_id' => 31,
                'order' => '6',
                'date' => '1768',
                'title' => 'Joins thirty-five other artists in forming the Royal Academy.',
                'text' => '',
            ],
            [
                'artist_id' => 31,
                'order' => '7',
                'date' => '1768',
                'title' => 'Lives with her father at Craven Building.',
                'text' => '',
            ],
            [
                'artist_id' => 31,
                'order' => '8',
                'date' => '1769',
                'title' => 'Begins exhibiting regularly in the annual Royal Academy.',
                'text' => '',
            ],
            [
                'artist_id' => 31,
                'order' => '9',
                'date' => '1780s',
                'title' => 'Appointed drawing instructor to Princess Elizabeth.',
                'text' => '',
            ],
            [
                'artist_id' => 31,
                'order' => '10',
                'date' => '1792',
                'title' => 'Receives her last commission from Queen Charlotte, an ambitious floral decorative scheme for the queen\'s villa at Frogmore. Receives more than £900, and the room retains its name: Moser Room.',
                'text' => '',
            ],
            [
                'artist_id' => 31,
                'order' => '11',
                'date' => '1793',
                'title' => 'Marries Captain Hugh Lloyd. Moser begins to exhibit work under her married name as an amateur.',
                'text' => '',
            ],
            [
                'artist_id' => 31,
                'order' => '12',
                'date' => '1802',
                'title' => 'Stops exhibiting at the Royal Academy after showing a total of thirty-six works.',
                'text' => '',
            ],
            [
                'artist_id' => 31,
                'order' => '13',
                'date' => '1805',
                'title' => 'Henry Fuseli nominates her as a candidate for president of the Royal Academy to replace Benjamin West.',
                'text' => '',
            ],
            [
                'artist_id' => 31,
                'order' => '14',
                'date' => '1810',
                'title' => 'Suffers a stroke and becomes paralyzed on her right side.',
                'text' => '',
            ],
            [
                'artist_id' => 31,
                'order' => '15',
                'date' => '1819',
                'title' => 'Dies on May 2 at age seventy-four.',
                'text' => '',
            ],
            // 32: Clara Peeters
            [
                'artist_id' => 32,
                'order' => '1',
                'date' => '1594',
                'title' => 'Born in Flanders.',
                'text' => '',
            ],
            [
                'artist_id' => 32,
                'order' => '2',
                'date' => '1608',
                'title' => 'Date of first signed work.',
                'text' => '',
            ],
            [
                'artist_id' => 32,
                'order' => '3',
                'date' => '1611/1612',
                'title' => 'Reaches the height of her career/productivity.',
                'text' => '',
            ],
            [
                'artist_id' => 32,
                'order' => '4',
                'date' => '1639',
                'title' => 'Marries Hendrick Joossen, and her professional career largely ceases.',
                'text' => '',
            ],
            [
                'artist_id' => 32,
                'order' => '5',
                'date' => '1657',
                'title' => 'Date of last known painting.',
                'text' => '',
            ],
            // 33: Maria Katharina Prestel
            [
                'artist_id' => 33,
                'order' => '1',
                'date' => '1747',
                'title' => 'Born in July in Nuremberg.',
                'text' => '',
            ],
            [
                'artist_id' => 33,
                'order' => '2',
                'date' => '1769',
                'title' => 'Marries art instructor Johann Gottlieb Prestel.',
                'text' => '',
            ],
            [
                'artist_id' => 33,
                'order' => '3',
                'date' => '1777',
                'title' => 'Gives birth to only child, daughter Ursula Magdalena.',
                'text' => '',
            ],
            [
                'artist_id' => 33,
                'order' => '4',
                'date' => '1786',
                'title' => 'Leaves husband and travels to England with daughter.',
                'text' => '',
            ],
            [
                'artist_id' => 33,
                'order' => '5',
                'date' => '1794',
                'title' => 'Dies on March 16 in London.',
                'text' => '',
            ],
            // 34: Adéle Romany
            [
                'artist_id' => 34,
                'order' => '1',
                'date' => '1769',
                'title' => 'Born in Paris.',
                'text' => '',
            ],
            [
                'artist_id' => 34,
                'order' => '2',
                'date' => '1790',
                'title' => 'Marries the miniaturist François-Antoine Romany.',
                'text' => '',
            ],
            [
                'artist_id' => 34,
                'order' => '3',
                'date' => '1793',
                'title' => 'Divorces François-Antoine Romany.',
                'text' => '',
            ],
            [
                'artist_id' => 34,
                'order' => '4',
                'date' => '1793',
                'title' => 'Debut at the Salon.',
                'text' => '',
            ],
            [
                'artist_id' => 34,
                'order' => '5',
                'date' => '1846',
                'title' => 'Dies in Paris.',
                'text' => '',
            ],
            // 35: Susan Penelope Rosse
            [
                'artist_id' => 35,
                'order' => '1',
                'date' => '1652',
                'title' => 'Born in England.',
                'text' => '',
            ],
            [
                'artist_id' => 35,
                'order' => '2',
                'date' => '1700',
                'title' => 'Died in London.',
                'text' => '',
            ],
            // 36: Ellen Wallace Sharples
            [
                'artist_id' => 36,
                'order' => '1',
                'date' => '1769',
                'title' => 'Born on March 4.',
                'text' => '',
            ],
            [
                'artist_id' => 36,
                'order' => '2',
                'date' => '1787',
                'title' => 'Marries portraitist James Sharples.',
                'text' => '',
            ],
            [
                'artist_id' => 36,
                'order' => '3',
                'date' => '1788',
                'title' => 'Moves to Liverpool.',
                'text' => '',
            ],
            [
                'artist_id' => 36,
                'order' => '4',
                'date' => '1793',
                'title' => 'Moves to Bath.',
                'text' => '',
            ],
            [
                'artist_id' => 36,
                'order' => '5',
                'date' => '1794',
                'title' => 'Moves to the United States.',
                'text' => '',
            ],
            [
                'artist_id' => 36,
                'order' => '6',
                'date' => '1801',
                'title' => 'Returns to Bath, fearing Franco-American war.',
                'text' => '',
            ],
            [
                'artist_id' => 36,
                'order' => '7',
                'date' => '1809',
                'title' => 'Returns to America.',
                'text' => '',
            ],
            [
                'artist_id' => 36,
                'order' => '8',
                'date' => '1810',
                'title' => 'Returns to England (Bristol) after her husband dies.',
                'text' => '',
            ],
            [
                'artist_id' => 36,
                'order' => '9',
                'date' => '1844',
                'title' => 'Founds the Bristol Fine Arts Academy.',
                'text' => '',
            ],
            [
                'artist_id' => 36,
                'order' => '10',
                'date' => '1849',
                'title' => 'Dies in Bristol.',
                'text' => '',
            ],
            // 37: Adriana Spilberg
            [
                'artist_id' => 37,
                'order' => '1',
                'date' => '1652',
                'title' => 'Born in Amsterdam.',
                'text' => '',
            ],
            [
                'artist_id' => 37,
                'order' => '2',
                'date' => '1661',
                'title' => 'Travels to Düsseldorf.',
                'text' => '',
            ],
            [
                'artist_id' => 37,
                'order' => '3',
                'date' => '1684',
                'title' => 'Marries Wilhelm Breekvelt.',
                'text' => '',
            ],
            [
                'artist_id' => 37,
                'order' => '4',
                'date' => '1697',
                'title' => 'Marries Eglon van der Neer.',
                'text' => '',
            ],
            [
                'artist_id' => 37,
                'order' => '5',
                'date' => '1703',
                'title' => 'Dies in Düsseldorf.',
                'text' => '',
            ],
            // 38: Gesina Ter Borch
            [
                'artist_id' => 38,
                'order' => '1',
                'date' => '1631',
                'title' => 'Born in Deventer.',
                'text' => '',
            ],
            [
                'artist_id' => 38,
                'order' => '2',
                'date' => '1647',
                'title' => 'Produces a watercolor album titled <i>Materi-boeck.</i>',
                'text' => '',
            ],
            [
                'artist_id' => 38,
                'order' => '3',
                'date' => '1652',
                'title' => 'Begins production on a second watercolor album (Rijksmuseum).',
                'text' => '',
            ],
            [
                'artist_id' => 38,
                'order' => '4',
                'date' => '1660',
                'title' => 'Begins third and final watercolor album (Rijksmuseum).',
                'text' => '',
            ],
            [
                'artist_id' => 38,
                'order' => '5',
                'date' => '1667',
                'title' => 'Works on a memorial portrait of her brother, Moses, who died in the Second Anglo-Dutch War.',
                'text' => '',
            ],
            [
                'artist_id' => 38,
                'order' => '6',
                'date' => '1690',
                'title' => 'Dies in Zwolle.',
                'text' => '',
            ],
            // 39: Anna Dorthea Therbush
            [
                'artist_id' => 39,
                'order' => '1',
                'date' => '1721',
                'title' => 'Born in Berlin.',
                'text' => '',
            ],
            [
                'artist_id' => 39,
                'order' => '2',
                'date' => '1742',
                'title' => 'Marries Ernst Friedrich Therbusch.',
                'text' => '',
            ],
            [
                'artist_id' => 39,
                'order' => '3',
                'date' => '1751',
                'title' => 'Father dies.',
                'text' => '',
            ],
            [
                'artist_id' => 39,
                'order' => '4',
                'date' => '1761–62',
                'title' => 'Completes works for Charles-Eugene, Count of Württemberg, in Stuuttgart.',
                'text' => '',
            ],
            [
                'artist_id' => 39,
                'order' => '5',
                'date' => '1762',
                'title' => 'Becomes an honorary member of the Stuttgart Academy of Fine Arts.',
                'text' => '',
            ],
            [
                'artist_id' => 39,
                'order' => '6',
                'date' => '1763–64',
                'title' => 'Completes works for Kurfürst Charles Theodore Wittelsbach in Mannheim.',
                'text' => '',
            ],
            [
                'artist_id' => 39,
                'order' => '7',
                'date' => '1765',
                'title' => 'Travels to Paris and meets Denis Diderot.',
                'text' => '',
            ],
            [
                'artist_id' => 39,
                'order' => '8',
                'date' => '1767',
                'title' => 'Elected a member of the Académie Royale.',
                'text' => '',
            ],
            [
                'artist_id' => 39,
                'order' => '9',
                'date' => '1767',
                'title' => 'Diderot claims to have modeled nude for Therbusch for his portrait.',
                'text' => '',
            ],
            [
                'artist_id' => 39,
                'order' => '10',
                'date' => '1768',
                'title' => 'Leaves Paris and travels to Brussels and Holland.',
                'text' => '',
            ],
            [
                'artist_id' => 39,
                'order' => '11',
                'date' => '1768',
                'title' => 'Named an honorary member of the Academy of Vienna.',
                'text' => '',
            ],
            [
                'artist_id' => 39,
                'order' => '12',
                'date' => '1768',
                'title' => 'Receives a commission for eight full-length portraits from the Prussian royal family.',
                'text' => '',
            ],
            [
                'artist_id' => 39,
                'order' => '13',
                'date' => '1769',
                'title' => 'Returns to Berlin after struggling to establish herself in Paris.',
                'text' => '',
            ],
            [
                'artist_id' => 39,
                'order' => '14',
                'date' => '1772',
                'title' => 'Husband dies.',
                'text' => '',
            ],
            [
                'artist_id' => 39,
                'order' => '15',
                'date' => '1773',
                'title' => 'Receives a commission from Catherine II of Russia to paint a portrait of Prussian royal family.',
                'text' => '',
            ],
            [
                'artist_id' => 39,
                'order' => '16',
                'date' => '1782',
                'title' => 'Dies in Berlin.',
                'text' => '',
            ],
            // 40: Anne Valayer-Coster
            [
                'artist_id' => 40,
                'order' => '1',
                'date' => '1744',
                'title' => 'Born on December 21 in Bièvre, France.',
                'text' => '',
            ],
            [
                'artist_id' => 40,
                'order' => '2',
                'date' => '1754',
                'title' => 'Moves to Paris.',
                'text' => '',
            ],
            [
                'artist_id' => 40,
                'order' => '3',
                'date' => '1762',
                'title' => 'Paints first recorded work, which has since been lost.',
                'text' => '',
            ],
            [
                'artist_id' => 40,
                'order' => '4',
                'date' => '1770',
                'title' => 'Admitted to the French Academy by a unanimous vote on July 28.',
                'text' => '',
            ],
            [
                'artist_id' => 40,
                'order' => '5',
                'date' => '1779',
                'title' => 'Gains patronage of Marie-Antoinette, queen of France.',
                'text' => '',
            ],
            [
                'artist_id' => 40,
                'order' => '6',
                'date' => '1780',
                'title' => 'Named official court painter to Queen Marie-Antoinette.',
                'text' => '',
            ],
            [
                'artist_id' => 40,
                'order' => '7',
                'date' => '1781',
                'title' => 'Marries Jean-Pierre Silvestre Coster, a wealthy lawyer.',
                'text' => '',
            ],
            [
                'artist_id' => 40,
                'order' => '8',
                'date' => '1781',
                'title' => 'Granted a studio in the Louvre.',
                'text' => '',
            ],
            [
                'artist_id' => 40,
                'order' => '9',
                'date' => '1818',
                'title' => 'Dies on February 28 in Paris.',
                'text' => '',
            ],
            // 41: Magdalena van de Passe
            [
                'artist_id' => 41,
                'order' => '1',
                'date' => '1600',
                'title' => 'Born in Copenhagen',
                'text' => '',
            ],
            [
                'artist_id' => 41,
                'order' => '2',
                'date' => '1634',
                'title' => 'Marries Frederick van Bevervoordt.',
                'text' => '',
            ],
            [
                'artist_id' => 41,
                'order' => '3',
                'date' => '1636',
                'title' => 'Frederick van Bevervoordt dies.',
                'text' => '',
            ],
            [
                'artist_id' => 41,
                'order' => '4',
                'date' => '1638',
                'title' => 'Dies in Utrecht.',
                'text' => '',
            ],
            // 42: Caterina van Hemessen
            [
                'artist_id' => 42,
                'order' => '1',
                'date' => '1527/28',
                'title' => 'Born in Antwerp.',
                'text' => '',
            ],
            [
                'artist_id' => 42,
                'order' => '2',
                'date' => '1553',
                'title' => 'Marries Kerstiaen de Moryn in Antwerp.',
                'text' => '',
            ],
            [
                'artist_id' => 42,
                'order' => '3',
                'date' => '1566',
                'title' => 'Dies in Antwerp.',
                'text' => '',
            ],
            // 43: Maria van Oosterwyck
            [
                'artist_id' => 43,
                'order' => '1',
                'date' => '1630',
                'title' => 'Born on August 20 in Nootdorp.',
                'text' => '',
            ],
            [
                'artist_id' => 43,
                'order' => '2',
                'date' => '1656',
                'title' => 'Trains in the studio of Jan Davidsz de Heem.',
                'text' => '',
            ],
            [
                'artist_id' => 43,
                'order' => '3',
                'date' => '1666',
                'title' => 'Moves to Amsterdam, where she works as assistant to Willem van Aelst.',
                'text' => '',
            ],
            [
                'artist_id' => 43,
                'order' => '4',
                'date' => '1693',
                'title' => 'Dies in Uitdam.',
                'text' => '',
            ],
            // 44: Mayken Verhulst
            [
                'artist_id' => 44,
                'order' => '1',
                'date' => '1518',
                'title' => 'Born in Mechelen.',
                'text' => '',
            ],
            [
                'artist_id' => 44,
                'order' => '2',
                'date' => '1538',
                'title' => 'Marries Pieter Coecke van Aelst.',
                'text' => '',
            ],
            [
                'artist_id' => 44,
                'order' => '3',
                'date' => '1550',
                'title' => 'Pieter Coecke van Aelst dies.',
                'text' => '',
            ],
            [
                'artist_id' => 44,
                'order' => '4',
                'date' => '1599',
                'title' => 'Dies in Mechelen.',
                'text' => '',
            ],
            // 45: Anna Roemers Visscher
            [
                'artist_id' => 45,
                'order' => '1',
                'date' => '1584',
                'title' => 'Born in Amsterdam.',
                'text' => '',
            ],
            [
                'artist_id' => 45,
                'order' => '2',
                'date' => '1624',
                'title' => 'Marries Dominicus Booth van Wesel.',
                'text' => '',
            ],
            [
                'artist_id' => 45,
                'order' => '3',
                'date' => '1625',
                'title' => 'Birth of her first son, Romanus.',
                'text' => '',
            ],
            [
                'artist_id' => 45,
                'order' => '4',
                'date' => '1626',
                'title' => 'Birth of her second son, Johannes.',
                'text' => '',
            ],
            [
                'artist_id' => 45,
                'order' => '5',
                'date' => '1646',
                'title' => 'Moves with family to Leiden.',
                'text' => '',
            ],
            [
                'artist_id' => 45,
                'order' => '6',
                'date' => '1651',
                'title' => 'Dies in Alkmaar.',
                'text' => '',
            ],
            // 46: Anna Waser
            [
                'artist_id' => 46,
                'order' => '1',
                'date' => '1678',
                'title' => 'Born in Zurich, Switzerland, the fifth child of a wealthy family.',
                'text' => '',
            ],
            [
                'artist_id' => 46,
                'order' => '2',
                'date' => '1689',
                'title' => 'Studies with Joseph Werner in Bern.',
                'text' => '',
            ],
            [
                'artist_id' => 46,
                'order' => '3',
                'date' => '1691',
                'title' => 'Completes <i>Self-Portrait aged Twelve</i> (Kunsthaus, Zürich), which shows her with her teacher or, possibly, her father.',
                'text' => '',
            ],
            [
                'artist_id' => 46,
                'order' => '4',
                'date' => '1696',
                'title' => 'Returns to Zurich.',
                'text' => '',
            ],
            [
                'artist_id' => 46,
                'order' => '5',
                'date' => '1699',
                'title' => 'Appointed court painter to Wilhelm Moritz von Solms-Braunfels at his Castle Braunfels in Hessen.',
                'text' => '',
            ],
            [
                'artist_id' => 46,
                'order' => '6',
                'date' => '1702',
                'title' => 'Returns to Zurich to care for her family.',
                'text' => '',
            ],
            [
                'artist_id' => 46,
                'order' => '7',
                'date' => '1708',
                'title' => 'Prepares a self-portrait for Jacob von Sandrart for his Teutsche Academie.',
                'text' => '',
            ],
            [
                'artist_id' => 46,
                'order' => '8',
                'date' => '1714',
                'title' => 'Dies from injuries obtained during a fall.',
                'text' => '',
            ],
            // 47: Michaelina Wautier
            [
                'artist_id' => 47,
                'order' => '1',
                'date' => '1617',
                'title' => 'Born in Mons.',
                'text' => '',
            ],
            [
                'artist_id' => 47,
                'order' => '2',
                'date' => 'ca. 1640',
                'title' => 'Moves to Brussels.',
                'text' => '',
            ],
            [
                'artist_id' => 47,
                'order' => '3',
                'date' => '1689',
                'title' => 'Dies in Brussels.',
                'text' => '',
            ],
            // 48: Alida Withoos
            [
                'artist_id' => 48,
                'order' => '1',
                'date' => '1661/1662',
                'title' => 'Born in Amersfoort',
                'text' => '',
            ],
            [
                'artist_id' => 48,
                'order' => '2',
                'date' => '1672',
                'title' => 'Moves with her family to Hoorn to escape French invasion of Utrecht.',
                'text' => '',
            ],
            [
                'artist_id' => 48,
                'order' => '3',
                'date' => '1701',
                'title' => 'Marries Andries Cornelisz van Dalen.',
                'text' => '',
            ],
            [
                'artist_id' => 48,
                'order' => '4',
                'date' => '1703',
                'title' => 'Relocates to Amsterdam after the death of her father.',
                'text' => '',
            ],
            [
                'artist_id' => 48,
                'order' => '5',
                'date' => '1730',
                'title' => 'Dies on December 5.',
                'text' => '',
            ],
            // 49: Margaretha Wulfraet
            [
                'artist_id' => 49,
                'order' => '1',
                'date' => '1678',
                'title' => 'Born in Arnhem.',
                'text' => '',
            ],
            [
                'artist_id' => 49,
                'order' => '2',
                'date' => '1681',
                'title' => 'Moves to Amsterdam',
                'text' => '',
            ],
            [
                'artist_id' => 49,
                'order' => '3',
                'date' => '1741',
                'title' => 'Returns to Arnhem.',
                'text' => '',
            ],
            [
                'artist_id' => 49,
                'order' => '4',
                'date' => '1760',
                'title' => 'Dies in Arnhem.',
                'text' => '',
            ],
            // 50: Maria Elisabeth Ziesenis
            [
                'artist_id' => 50,
                'order' => '1',
                'date' => '1744',
                'title' => 'Born in Frankfurt am Main.',
                'text' => '',
            ],
            [
                'artist_id' => 50,
                'order' => '2',
                'date' => '1749–61',
                'title' => 'Active in Mannheim.',
                'text' => '',
            ],
            [
                'artist_id' => 50,
                'order' => '3',
                'date' => '1761–74',
                'title' => 'Active in Hannover.',
                'text' => '',
            ],
            [
                'artist_id' => 50,
                'order' => '4',
                'date' => '1774',
                'title' => 'Returns to Mannheim.',
                'text' => '',
            ],
            [
                'artist_id' => 50,
                'order' => '5',
                'date' => '1776',
                'title' => 'Marries Johann Bado Lampe.',
                'text' => '',
            ],
            [
                'artist_id' => 50,
                'order' => '6',
                'date' => '1780',
                'title' => 'Becomes a member of the Kassel Akademie.',
                'text' => '',
            ],
            [
                'artist_id' => 50,
                'order' => '7',
                'date' => '1796',
                'title' => 'Dies in Hannover.',
                'text' => '',
            ],
        ]);
    }
}
